galaxy_info:
  author: etke.cc
  company: etke.cc
  role_name: ntfy
  namespace: etkecc
  description: Ntfy
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: EL
      versions:
        - 7
  license: GPL-3.0-or-later
  min_ansible_version: '2.1'
